spring.application.name=website
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://lgplkntgjzmrmasdhbqi.supabase.co/auth/v1/.well-known/jwks.json
logging.file.name=logs/application.log

supabase.url=https://lgplkntgjzmrmasdhbqi.supabase.co
supabase.publishable-key=${SUPABASE_PUBLISHABLE_KEY}
supabase.secret-key=${SUPABASE_SECRET_KEY}

server.port=8080

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=alphapm