spring.application.name=website
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://lgplkntgjzmrmasdhbqi.supabase.co/auth/v1/.well-known/jwks.json
logging.file.name=logs/application.log
supabase.url=https://lgplkntgjzmrmasdhbqi.supabase.co
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY}
supabase.anon-key=${SUPABASE_ANON_KEY}