spring.application.name=website
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://lgplkntgjzmrmasdhbqi.supabase.co/auth/v1/.well-known/jwks.json

logging.level.com.nimbusds=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG

supabase.url=https://lgplkntgjzmrmasdhbqi.supabase.co
supabase.publishable-key=${SUPABASE_PUBLISHABLE_KEY}
supabase.secret-key=${SUPABASE_SECRET_KEY}

server.port=8080

server.ssl.enabled=true
server.ssl.key-store=file:/home/opc/keystore.p12
server.ssl.key-store-password=SAsadGe4#321!
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=alphapm
